@startuml
class Netflix {
- title: string
- director: string
- runtime: int
- release_date: date
- runtime: int
+ search(title: string, director: string, release_date: date, genre: string, runtime: int): List<Netflix>
+ play(): void
+ add_netflix(title: string, director: string, release_date: date, genre: string, runtime: int): void
+ delete_netflix(title: string, director: string, release_date: date, genre: string, runtime: int): void
}


class User{
- username: string
- password: string
- email: string
- payment_info: PaymentInfo
- watchlist: List<Netflix>
+ add_to_watchlist(netflix: Netflix): void
+ remove_from_watchlist(netflix: Netflix): void
+ search(title: string, director: string, release_date: date, genre: string, runtime: int): List<Netflix>
+ get_username(): string
+ set_username(username: string): void
+ get_password(): string
+ set_password(password: string): void
+ get_email(): string
+ set_email(email: string): void
+ get_payment_info(): PaymentInfo
+ set_payment_info(payment_info: PaymentInfo): void
+ get_watchlist(): List<Netflix>
+ add_to_watchlist(netflix: Netflix): void
}

class TypeNetflix{
- type_id: int
- genre: string
}


Class Role{
- role_id: int
- name: string

}

class   PaymentInfo {
- card_number: string
- expiration_date: date
- cvv: string
}

Netflix -d- TypeNetflix : Etre
User -u-o PaymentInfo : Possede
User -d- Role : Avoir
Netflix -d- User : regarder
@enduml